# src/config/cifar100.yaml

dataset:
  name: 'CIFAR100'
  data_dir: '/path/to/cifar100'
  image_size: 224
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]

num_stages: 3

mg_graph:
  depth: 2
  labels:
    - 'animal'
    - 'plant'
    - 'mammal'
    - 'bird'
    - 'flower'
    - 'tree'
    - 'dog'
    - 'cat'
    - 'eagle'
    - 'sparrow'
    - 'rose'
    - 'oak'

model:
  prompt_dim: 768  # Should match the hidden size of Swin Transformer

optimizer:
  type: 'adamw'
  lr: 1e-4
  weight_decay: 1e-4
  # momentum: 0.9  # Only needed for SGD

scheduler:
  type: 'step'  # 'step', 'cosine', 'cosine_restart'
  step_size: 30
  gamma: 0.1
  # For cosine scheduler:
  # T_max: 100
  # For cosine_restart:
  # T_0: 10
  # T_mult: 2

loss:
  alpha: [1.0, 1.0, 1.0]  # Weights for L_cls per stage
  beta: [0.0, 1.0, 1.0]   # Weights for L_coh per stage (start from stage 2)
  gamma: [1.0, 1.0, 1.0]  # Weights for L_eval per stage
  lambda_eval: 1.0        # Weight for evaluator loss

mixup:
  alpha: 0.8
  cutmix_alpha: 1.0
  label_smoothing: 0.1

log_dir: './logs'
num_epochs: 100
batch_size: 64
num_workers: 4
log_interval: 100
