MODE: 'train'  # or 'eval'

DATASET:
  NAME: 'cifar100'
  NUM_CLASSES: 100
  DATA_PATH: '../data'
  HIERARCHY: './resources/hiers/cifar100.json'
  IMAGE_SIZE: 224

MODEL:
  MODEL_PATH: './outputs/'
  BACKBONE_ROOT: './resources/weights/smt_base_cifar100.pth'
  CLIP_ROOT: './resources/weights/ViT-B-32.pt'
  EMBED_DIMS: [256, 512]
  NUM_HEADS: [8, 16]
  MLP_RATIOS: [4, 2]
  NUM_DECODER_LAYERS: 2
  BACKBONE:
    NAME: 'smt'
    DEPTHS: [4, 6, 28, 2]
    MLP_RATIOS: [8, 6, 4, 2]
    CA_NUM_HEADS: [4, 4, 4, -1]
    SA_NUM_HEADS: [-1, -1, 8, 16]
    QKV_BIAS: True
    DROP_PATH_RATE: 0.3
    CA_ATTENTIONS: [1, 1, 1, 0]
    IN_CHANS: 7
    EXPAND_RATIO: 2

OPTIMIZER:
  NAME: 'adamw'
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
  # MOMENTUM: 0.9  # Only needed for SGD

SCHEDULER:
  NAME: 'cosine'  # 'cosine', 'step', 'cosine_restart'
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  WARMUP_LR: 1e-7
  MIN_LR: 1e-6
  DECAY_EPOCHS: 30
  DECAY_RATE: 0.1
  # Additional scheduler parameters can be added as needed

LOSS:
  LAMBDA_MERO: 1.0
  LAMBDA_BASE: 1.0
  LAMBDA_COH: 1.0

TRAIN:
  START_EPOCH: 0
  RESUME: ''

AUG:
  COLOR_JITTER: 0.4
  AUTO_AUGMENT: 'rand-m9-mstd0.5-inc1'
  REPROB: 0.
  REMODE: 'pixel'
  RECOUNT: 1
  MIXUP: 0.2  #0.8
  CUTMIX: 1.0  #1.0
  CUTMIX_MINMAX: null
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.5
  MIXUP_MODE: 'batch'

LOG_DIR: './logs'
NUM_EPOCHS: 300
BATCH_SIZE: 64
NUM_WORKERS: 4
AMP_ENABLE: False
